version: '3.8'

services:
  openxc7-dev:
    image: regymm/openxc7
    container_name: fpga_openxc7_env
    privileged: true
    volumes:
      - ..:/mnt/workspace
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /mnt/workspace
    command: tail -f /dev/null